# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='img/Producto')),
                ('tipo_de_bodega', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=150)),
                ('telefono', models.IntegerField()),
                ('antiguedad', models.CharField(max_length=150)),
                ('superficie', models.DecimalField(max_digits=10, decimal_places=5)),
                ('banos', models.IntegerField()),
                ('estacionamiento', models.CharField(max_length=2)),
                ('niveles', models.IntegerField()),
                ('caracteristicas_adicionales', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Camionetas',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='img/Producto', blank=True)),
                ('ubicacion', models.CharField(max_length=150)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
                ('caracteristicas_adicionales', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Casas',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='img/Producto')),
                ('estado', models.CharField(max_length=25)),
                ('calle', models.CharField(max_length=50)),
                ('numero', models.SmallIntegerField()),
                ('telefono', models.IntegerField()),
                ('antiguedad', models.CharField(max_length=25)),
                ('banos', models.SmallIntegerField()),
                ('recamaras', models.SmallIntegerField()),
                ('superficie', models.DecimalField(max_digits=10, decimal_places=5)),
                ('amueblado', models.CharField(max_length=25)),
                ('tipo_terreno', models.CharField(max_length=25)),
                ('conservacion', models.CharField(max_length=25)),
                ('estacionamiento', models.CharField(max_length=25)),
                ('luminosidad', models.CharField(max_length=25)),
                ('niveles', models.SmallIntegerField()),
                ('titulo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('categoria', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Choferes',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='img/Producto', blank=True)),
                ('ubicacion', models.CharField(max_length=150)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
                ('caracteristicas_adicionales', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Cuartos',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='img/Producto')),
                ('ubicacion', models.CharField(max_length=150)),
                ('telefono', models.IntegerField()),
                ('banos', models.IntegerField()),
                ('superficie', models.DecimalField(max_digits=10, decimal_places=5)),
                ('amueblado', models.BooleanField()),
                ('caracteristicas_adicionales', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='img/Producto')),
                ('ubicacion', models.CharField(max_length=150)),
                ('telefono', models.IntegerField()),
                ('antiguedad', models.IntegerField()),
                ('superficie', models.DecimalField(max_digits=10, decimal_places=5)),
                ('disposicion', models.CharField(max_length=25)),
                ('balcon', models.CharField(max_length=2)),
                ('banos', models.SmallIntegerField()),
                ('cantidad_pisos', models.SmallIntegerField()),
                ('conservacion', models.CharField(max_length=30)),
                ('elevador', models.CharField(max_length=10)),
                ('estacionamiento', models.CharField(max_length=2)),
                ('horario_contacto', models.DateField()),
                ('metros_jardin', models.DecimalField(max_digits=10, decimal_places=5)),
                ('recamaras', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Edificios',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='img/Producto')),
                ('ubicacion', models.CharField(max_length=150)),
                ('telefono', models.IntegerField()),
                ('superficie', models.DecimalField(max_digits=10, decimal_places=5)),
                ('clasificacion_edificio', models.CharField(max_length=50)),
                ('banos', models.IntegerField()),
                ('antiguedad', models.CharField(max_length=150)),
                ('pisos', models.IntegerField()),
                ('elevador', models.BooleanField()),
                ('conservacion', models.CharField(max_length=20)),
                ('estacionamiento', models.CharField(max_length=2)),
                ('metros_jardin', models.DecimalField(max_digits=10, decimal_places=5)),
                ('niveles', models.IntegerField()),
                ('departamentos', models.IntegerField()),
                ('caracteristicas_adicionales', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Haciendas',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='img/Producto')),
                ('ubicacion', models.CharField(max_length=150)),
                ('telefono', models.IntegerField()),
                ('tipo_de_finca', models.CharField(max_length=50)),
                ('superficie', models.DecimalField(max_digits=10, decimal_places=5)),
                ('banos', models.IntegerField()),
                ('antiguedad', models.CharField(max_length=150)),
                ('recamaras', models.IntegerField()),
                ('conservacion', models.CharField(max_length=20)),
                ('forma_del_terreno', models.CharField(max_length=20)),
                ('metros_jardin', models.DecimalField(max_digits=10, decimal_places=5)),
                ('caracteristicas_adicionales', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Locales',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='img/Producto')),
                ('ubicacion', models.CharField(max_length=150)),
                ('telefono', models.IntegerField()),
                ('antiguedad', models.CharField(max_length=150)),
                ('superficie', models.IntegerField()),
                ('metros_frente', models.DecimalField(max_digits=10, decimal_places=5)),
                ('metros_fondo', models.DecimalField(max_digits=10, decimal_places=5)),
                ('tipo_de_obra', models.CharField(max_length=20)),
                ('ubicacion_en_plaza', models.CharField(max_length=20)),
                ('banos', models.IntegerField()),
                ('conservacion', models.CharField(max_length=20)),
                ('elevador', models.CharField(max_length=10)),
                ('estacionamiento', models.CharField(max_length=2)),
                ('horario_contacto', models.DateField()),
                ('niveles', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LocalesComerciales',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='img/Producto')),
                ('ubicacion', models.CharField(max_length=150)),
                ('telefono', models.IntegerField()),
                ('antiguedad', models.CharField(max_length=150)),
                ('superficie', models.DecimalField(max_digits=10, decimal_places=5)),
                ('metros_fondo', models.DecimalField(max_digits=10, decimal_places=5)),
                ('metros_frente', models.DecimalField(max_digits=10, decimal_places=5)),
                ('piso_en_que_se_encuentra', models.IntegerField()),
                ('tipo_obra', models.CharField(max_length=20)),
                ('ubicacion_en_plaza', models.CharField(max_length=20)),
                ('banos', models.IntegerField()),
                ('conservacion', models.CharField(max_length=20)),
                ('elevador', models.BooleanField()),
                ('estacionamiento', models.CharField(max_length=2)),
                ('caracteristicas_adicionales', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MensajeriayPaqueteria',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='img/Producto')),
                ('ubicacion', models.CharField(max_length=150)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
                ('caracteristicas_adicionales', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Mudanzas',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='img/Producto')),
                ('ubicacion', models.CharField(max_length=150)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
                ('caracteristicas_adicionales', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='NavesIndustriales',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='img/Producto')),
                ('ubicacion', models.CharField(max_length=150)),
                ('telefono', models.IntegerField()),
                ('antiguedad', models.CharField(max_length=150)),
                ('metros_frente', models.DecimalField(max_digits=10, decimal_places=5)),
                ('banos', models.IntegerField()),
                ('metros_cuadrados_bodega', models.DecimalField(max_digits=10, decimal_places=5)),
                ('metros_cuadrados_oficina', models.DecimalField(max_digits=10, decimal_places=5)),
                ('area_carga_descarga', models.DecimalField(max_digits=10, decimal_places=5)),
                ('area_maniobras', models.DecimalField(max_digits=10, decimal_places=5)),
                ('altura_inmueble', models.DecimalField(max_digits=10, decimal_places=5)),
                ('capacidad_de_carga', models.DecimalField(max_digits=10, decimal_places=5)),
                ('fondo', models.DecimalField(max_digits=10, decimal_places=5)),
                ('tipo_techo', models.CharField(max_length=10)),
                ('niveles', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Oficinas',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='img/Producto')),
                ('ubicacion', models.CharField(max_length=150)),
                ('telefono', models.IntegerField()),
                ('antiguedad', models.CharField(max_length=150)),
                ('superficie', models.DecimalField(max_digits=10, decimal_places=5)),
                ('piso_en_que_se_encuentra', models.IntegerField()),
                ('banos', models.IntegerField()),
                ('conservacion', models.CharField(max_length=20)),
                ('elevador', models.BooleanField()),
                ('estacionamiento', models.CharField(max_length=2)),
                ('cercanias', models.CharField(max_length=50)),
                ('caracteristicas_adicionales', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Otros',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='img/Producto', blank=True)),
                ('ubicacion', models.CharField(max_length=150)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
                ('caracteristicas_adicionales', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Remolques',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='img/Producto', blank=True)),
                ('ubicacion', models.CharField(max_length=150)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
                ('caracteristicas_adicionales', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Taxis',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='img/Producto', blank=True)),
                ('ubicacion', models.CharField(max_length=150)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
                ('caracteristicas_adicionales', models.CharField(max_length=250)),
            ],
        ),
    ]
